api/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('atencion/', include('atencion.api'))
]

atencion/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('solicitar/<interprete>', views.SolicitudView.as_view(), name="solicitar_atencion"),
    path('detalle/<int:id>', views.detalleAtencion, name="detalle_atencion"),
    path('modificar/<pk>', views.ModificarAtencionView.as_view(), name="modificar_atencion"),
    path('listado',views.listadoAtenciones, name="listado_atenciones"),
    path('aceptar/<int:pk>', views.aceptar_atencion, name="aceptar_atencion"),
    path('sesion/<int:pk>', views.SesionInterpreteDetalle.as_view(), name="detalle_sesion")
]

trabajo2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf  import settings

handler404 = 'interlancer.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('interlancer.urls')),
    path('usuario/', include('usuario.urls')),
    path('atencion/', include('atencion.urls')),
    path('review/', include('review.urls')),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atencion/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime

from usuario.models import Solicitante, Interprete, Persona
from especialidad.models import Especialidad

# Create your models here.
class Atencion(models.Model):
    ATENCION_STATE_CHOICES = ((0, 'solicitado'), (1, 'aceptado'), (2, 'confirmado'), (3, 'sesion'), (4, 'finalizado'), (5, 'cancelado'))

    # FK
    solicitante = models.ForeignKey(Solicitante, on_delete=models.DO_NOTHING, related_name='atenciones')
    interprete = models.ForeignKey(Interprete, on_delete=models.DO_NOTHING, related_name='atenciones', null=True, blank=True)
    # Datos de la atencion
    especialidad = models.ForeignKey(Especialidad, on_delete=models.DO_NOTHING, related_name='atenciones')
    titulo = models.CharField(max_length=255)
    descripcion = models.TextField()
    duracion = models.DecimalField(max_digits = 3 ,decimal_places = 1, default = 0.5)
    # TODO Modulo reserva 
    fecha_reserva = models.DateTimeField(blank=True, null=True)
    # Metadatos de procesos
    fecha_inicio_sesion = models.DateTimeField(blank=True, null=True)
    fecha_termino = models.DateTimeField(blank=True, null=True)
    estado = models.PositiveSmallIntegerField(choices=ATENCION_STATE_CHOICES, default=0)
    fecha_creacion = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name_plural = 'atenciones'

    def get_absolute_url(self):
        return reverse('detalle_atencion', kwargs={'id': self.pk}) 
        #return reverse('listado_atenciones')

    def __str__(self):
        return f'Atencion #{self.pk} - {self.titulo}'

    def aceptar(self, interprete):
        """
            Cambia el estado de la atención actual

            interprete (Interprete) - El interprete que realiza la atencion
        """

        self.interprete = interprete
        # self.fecha_atencion = datetime.now()
        self.estado = 1
        self.save()

    def confirmar(self):
        # TODO logica de cobro
        self.estado = 2
        self.save()

    def iniciar_sesion(self):
        # TODO logica inicio sesion
        self.estado = 3
        self.save()

    def finalizar(self):
        """
            Termina la atencion, finalizando su estado
        """

        self.estado = 4
        self.fecha_termino = datetime.now()
        self.save()

    def cancelar(self):
        self.estado = 5
        self.save()

    def esta_finalizada(self):
        return self.estado == 4
            
class Sesion(models.Model):
    sesion_id = models.IntegerField()
    atencion = models.OneToOneField(Atencion, on_delete=models.CASCADE, related_name='sesion')
    host_url = models.URLField(verbose_name='Link para iniciar')
    join_url = models.URLField(verbose_name='Link para unirse')

    def terminar_sesion(self):
        self.atencion.fecha_termino = datetime.now()
        self.estado = 4
        self.atencion.save()

atencion/forms.py
from django import forms
from .models import Atencion
from .widgets import BootstrapDateTimePickerInputCreate,BootstrapDateTimePickerInputModify

class SolicitudForm(forms.ModelForm):
    class Meta:
        model = Atencion
        exclude = ['fecha_inicio_sesion', 'fecha_termino', 'estado']
        widgets = {
            'solicitante' : forms.HiddenInput(),
            'interprete' : forms.HiddenInput(),
            'fecha_creacion' : forms.HiddenInput(),
            'fecha_reserva' : BootstrapDateTimePickerInputCreate(),
        }

    def __init__(self, *args, **kwargs):
        especialidades = kwargs.pop('especialidades')
        super(SolicitudForm, self).__init__(*args, **kwargs)
        self.fields['especialidad'].queryset = especialidades

class ModificarForm(forms.ModelForm):
    class Meta:
        model = Atencion
        exclude = ['fecha_inicio_sesion', 'fecha_termino', 'solicitante', 'interprete', 'estado']
        widgets = {
            'fecha_reserva': BootstrapDateTimePickerInputModify(),
        }

atencion/views.py
from django.shortcuts import render,redirect,reverse, get_object_or_404
from django.views.generic import CreateView,UpdateView,DetailView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from .forms import SolicitudForm,ModificarForm
from .models import Atencion, Sesion
from usuario.models import Interprete
from usuario.mixins import InterpreteRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from rest_framework.views import APIView
from rest_framework.decorators import permission_classes
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework import status
from .services import iniciar_sesion_instantanea
from .serializers import AtencionSerializer
# Create your views here.

class SolicitudView(LoginRequiredMixin,CreateView):
    model = Atencion
    template_name = 'atencion/solicitar.html'
    form_class = SolicitudForm

    
    # def __init__(self, **kwargs):
    #     super(SolicitudView, self).__init__(**kwargs)
    #     self.interprete = kwargs['interprete']

    def get_form_kwargs(self):
        kwargs = super(SolicitudView, self).get_form_kwargs()
        rut_interprete = self.kwargs.get('interprete')
        especialidades = Interprete.objects.get(rut=rut_interprete).especialidades.all()
        kwargs['especialidades'] = especialidades
        return kwargs

    def get_initial(self):
        return {'interprete':self.kwargs.get('interprete'),'solicitante':self.request.user.solicitante}

    def get_context_data(self, **kwargs):
        ctx = super(SolicitudView, self).get_context_data(**kwargs)
        u_interprete = Interprete.objects.get(rut=self.kwargs['interprete'])
        ctx['interprete'] = u_interprete
        return ctx

    def form_valid(self, form):
        form.save(self.request.user)
        return super(SolicitudView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return self.object.get_absolute_url()


class ModificarAtencionView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Atencion
    template_name = 'atencion/modificarAtencion.html'
    form_class = ModificarForm
    success_message = 'La solicitud se ha modificado con éxito'
    
    def get_success_url(self, **kwargs):
        return self.object.get_absolute_url()


def detalleAtencion(request,id):
    ctx = {}
    ctx['atencion'] = Atencion.objects.get(id=id)
    ctx['r'] = [5,4,3,2,1]
    return render(request, 'atencion/detalleAtencion.html',ctx)

def listadoAtenciones(request):
    ctx = {}
    if request.method == 'GET':
        atenciones = request.user.solicitante.atenciones.exclude(estado=5)
        ctx['listaAtenciones'] = atenciones
        return render(request, 'atencion/atenciones.html',ctx)
    if request.method == 'POST':
        id_atencion = request.POST['id']
        if 'view' in request.POST:
            return redirect('detalle_atencion',id_atencion)
        if 'edit' in request.POST:
            return redirect('modificar_atencion',id_atencion)
        if 'delete' in request.POST:
            atencion = Atencion.objects.get(id=id_atencion)
            atencion.cancelar()
            messages.success(request, 'Se ha cancelado la atención')
            return redirect('listado_atenciones')
            
def aceptar_atencion(request, pk):
    if hasattr(request.user,'interprete'):
        atencion = get_object_or_404(Atencion, pk = pk)
        if not hasattr(atencion, 'sesion') and atencion.estado == 2:
            atencion.confirmar()
            sesion = iniciar_sesion_instantanea(atencion)
            messages.success(request, 'Sesion creada con exito! Revise su correo.')
        else:
            messages.warning(request, 'Ya existe una sesión activa para esta solicitud.')
    else:
        messages.error(request, 'No tienes acceso a esta ruta.')
    return redirect('dash')

class SesionInterpreteDetalle(LoginRequiredMixin, InterpreteRequiredMixin, DetailView):
    model = Sesion
    template_name = "sesion/detalle.html"

@permission_classes((permissions.AllowAny,))
class AtencionList(APIView):
    def get(self, request, format=None):
        atenciones = Atencion.objects.exclude(estado=5)
        serializer = AtencionSerializer(atenciones, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = AtencionSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@permission_classes((permissions.AllowAny,))
class AtencionDetailApi(APIView):
    def get_object(self, pk):
        try:
            return Atencion.objects.get(pk=pk)
        except Atencion.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        atencion = self.get_object(pk)
        serializer = AtencionSerializer(atencion)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        atencion = self.get_object(pk)
        serializer = AtencionSerializer(atencion, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        atencion = self.get_object(pk)
        atencion.cancelar()
        return Response(status=status.HTTP_204_NO_CONTENT)

atencion/templates/atencion/atenciones.html
{% extends 'usuario/solicitante/solicitanteNav.html'%}

{% block title %}Listado Atenciones{% endblock title %}

{% block content_title %}Listado Atenciones{% endblock %}

{% block content_breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'dash' %}">Inicio</a></li>
<li class="breadcrumb-item active" aria-current="page">Listado Atenciones</li>
{% endblock %}

{% block content %}
<div class="card card-dark">
    <!-- Título -->
    <div class="card-header">
        <h3 class="card-title">Atenciones</h3>
    </div>
    <div class="card-body">
        <div id="tabla_atenciones_wrapper" class="dataTables_wrapper dt-bootstrap4">
            <div class="row">
                <div class="col-sm-12">
                    <table id="tabla_atenciones" class="table table-bordered table-hover  " role="grid"
                        aria-describedby="tabla_atenciones_info">
                        <thead>
                            <tr role="row">
                                <th class="sorting" tabindex="0" rowspan="1" colspan="1"
                                    aria-label="ID">ID</th>
                                <th class="sorting" tabindex="0" rowspan="1" colspan="1"
                                    aria-label="">Intérprete</th>
                                <th class="sorting" tabindex="0" rowspan="1" colspan="1"
                                    aria-label="">Especialidad</th>
                                <th class="sorting" tabindex="0" rowspan="1" colspan="1"
                                    aria-label="">Título</th>
                                <th class="sorting" tabindex="0" rowspan="1" colspan="1"
                                    aria-label="">Fecha de Creación</th>
                                <th class="sorting" tabindex="0" rowspan="1" colspan="1"
                                    aria-label="">Estado</th>
                                <th class="sorting" tabindex="0" rowspan="1" colspan="1"
                                    aria-label="">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for atencion in listaAtenciones %}
                            <tr role="row" class="{% cycle 'odd' 'even' %}"
                                >
                                <td>{{atencion.id}}</td>
                                <td>{{atencion.interprete}}</td>
                                <td>{{atencion.especialidad}}</td>
                                <td>{{atencion.titulo}}</td>
                                <td>{{atencion.fecha_creacion}}</td>
                                <td>{{atencion.get_estado_display.capitalize}}</td>
                                <td class="text-right py-0 align-middle">
                                    <form method="POST" class="text-center">
                                        {% csrf_token %}
                                        <input type="text" name="id" hidden value="{{atencion.id}}">
                                        <div class="btn-group p-2 text-white">
                                            <button type="submit" name="view" class="btn btn-info">
                                                <ion-icon name="eye" class="icon-s mt-1"></ion-icon>
                                            </button>
                                            <button type="submit" name="edit" class="btn btn-success">
                                                <ion-icon name="create" class="icon-s mt-1"></ion-icon>
                                            </button>
                                            <button type="submit" name="delete" class="btn btn-danger">
                                                <ion-icon name="trash" class="icon-s mt-1"></ion-icon>
                                            </button>
                                        </div>
                                    </form>

                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr role="row">
                                <th rowspan="1" colspan="1">ID</th>
                                <th rowspan="1" colspan="1">Intérprete</th>
                                <th rowspan="1" colspan="1">Especialidad</th>
                                <th rowspan="1" colspan="1">Título</th>
                                <th rowspan="1" colspan="1">Descripcion</th>
                                <th rowspan="1" colspan="1">Estado</th>
                                <th rowspan="1" colspan="1">Acciones</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block scripts %}
    <script>
        $(document).ready(function() {
            $('#tabla_atenciones').DataTable({
                "pagingType": "simple_numbers",
                language: {
                    search: "Filtrar",
                    paginate: {
                        first: "Inicio",
                        previous: "Anterior",
                        next: "Siguiente",
                        last: "Fin"
                    },
                    info: "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                    lengthMenu: "Mostrar _MENU_ entradas"
                }
            });
        });
    </script>
{% endblock scripts %}
    

atencion/templates/atencion/detalleAtencion.html
{% extends 'usuario/solicitante/solicitanteNav.html' %}

{% block title %}Detalle Atención{% endblock title %}

{% block content_title %}Detalle Atención{% endblock %}

{% block content_breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'dash' %}">Inicio</a></li>
<li class="breadcrumb-item"><a href="{% url 'listado_atenciones' %}">Listado Atenciones</a></li>
<li class="breadcrumb-item active" aria-current="page">Detalle #{{atencion.id}}</li>
{% endblock %}

{% block content %}
<div class="card card-dark">
  <!-- Título -->
  <div class="card-header">
    <h3 class="card-title">{{atencion.titulo}}</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
        <div class="row">
          <div class="col-12 col-sm-4">
            <div class="info-box bg-light">
              <div class="info-box-content">
                <span class="info-box-text text-center text-muted">Id de atención</span>
                <span class="info-box-number text-center text-muted mb-0">{{atencion.id}}</span>
              </div>
            </div>
          </div>
          <div class="col-12 col-sm-4">
            <div class="info-box bg-light">
              <div class="info-box-content">
                <span class="info-box-text text-center text-muted">Fecha de Reserva</span>
                <span class="info-box-number text-center text-muted mb-0">{{atencion.fecha_reserva}}</span>
              </div>
            </div>
          </div>
          <div class="col-12 col-sm-4">
            <div class="info-box 
                      {% if atencion.estado == 0 %}
                        bg-blue
                      {% elif atencion.estado == 1 %}
                        bg-olive
                      {% elif atencion.estado == 2 %}
                        bg-success
                      {% elif atencion.estado == 3 %}
                        bg-light
                      {% endif %}
                      ">
              <div class="info-box-content">
                <span class="info-box-text text-center">Estado</span>
                <span
                  class="info-box-number text-center">{{atencion.get_estado_display.capitalize}}{% if atencion.estado == 3 %}
                  <ion-icon name="ellipse" class="text-red ml-2"></ion-icon>{% endif %}</span>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <h4>Más información</h4>
            <div class="row">
              <div class="col-md-6">
                <div class="card card-lightblue">
                  <div class="card-header">
                    <h3 class="card-title">Descripción</h3>

                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                          class="fas fa-minus"></i>
                      </button>
                    </div>
                    <!-- /.card-tools -->
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    {{atencion.descripcion}}
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
              <div class="col-md-6">
                <div class="card card-lightblue">
                  <div class="card-header">
                    <h3 class="card-title">Especialidad</h3>

                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                          class="fas fa-minus"></i>
                      </button>
                    </div>
                    <!-- /.card-tools -->
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    {{atencion.especialidad}}
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="card card-lightblue">
                  <div class="card-header">
                    <h3 class="card-title">Fecha de Creación</h3>
    
                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                          class="fas fa-minus"></i>
                      </button>
                    </div>
                    <!-- /.card-tools -->
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    {{atencion.fecha_creacion}}
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
              <div class="col-md-6">
                <div class="card card-lightblue">
                  <div class="card-header">
                    <h3 class="card-title">Duración</h3>
    
                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                          class="fas fa-minus"></i>
                      </button>
                    </div>
                    <!-- /.card-tools -->
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    {{atencion.duracion}} Hrs
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="card card-lightblue">
                  <div class="card-header">
                    <h3 class="card-title">Fecha de Sesión</h3>
    
                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                          class="fas fa-minus"></i>
                      </button>
                    </div>
                    <!-- /.card-tools -->
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    
                    {% if atencion.fecha_sesion %}
                      {{atencion.fecha_inicio_sesion}}
                    {% else %}
                      Por realizarse
                    {% endif %}
                      
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
              <div class="col-md-6">
                <div class="card card-lightblue">
                  <div class="card-header">
                    <h3 class="card-title">Fecha de término de Sesión</h3>
    
                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                          class="fas fa-minus"></i>
                      </button>
                    </div>
                    <!-- /.card-tools -->
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    
                    {% if atencion.fecha_termino %}
                      {{atencion.fecha_termino}}
                    {% else %}
                      Por realizarse
                    {% endif %}
                      
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
            </div>
          </div>
          
        </div>
        
      </div>
      <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
        <h3 class="text-primary">
          <ion-icon name="hand-left-outline"></ion-icon> Intérprete
        </h3>
        <div class="col-12 align-items-stretch">
          <div class="card bg-light">
            <div class="card-header border-bottom-0 p-0 pt-1 pb-1 col-12 col-sm-8 pl-sm-5 pr-sm-5">

            </div>
            <div class="card-body pt-0">
              <div class="row">
                <div class="col-lg-7 col-sm-8 pt-sm-2 text-sm-center">
                  <div class="rating pb-sm-4 pb-lg-1">
                    {% for i in r %}
                    {% if i == atencion.interprete.calificacion %}
                    <input type="radio" name="rating" value="{{i}}" id="{{i}}" checked="true" disabled="true"><label
                      for="{{i}}">☆</label>
                    {% else %}
                    <input type="radio" name="rating" value="{{i}}" id="{{i}}" disabled="true"><label
                      for="{{i}}">☆</label>
                    {% endif %}
                    {% endfor %}
                  </div>
                  <h2 class="lead"><b>{{atencion.interprete}}</b></h2>
                  <p class="text-muted text-sm"><b>Especialidades: </b>
                    {% for esp in atencion.interprete.especialidades.all %}
                    {{esp.especialidad.capitalize}} {% if not forloop.last %}/{% endif %}
                    {% endfor %}
                  </p>
                  <ul class="ml-4 mb-0 fa-ul text-muted">
                    <li class="small"><span class="fa-li">
                        <ion-icon name="mail-outline" class="icon-s"></ion-icon>
                      </span> E-mail: {{atencion.interprete.correo}}</li>
                    <li class="small"><span class="fa-li">
                        <ion-icon name="phone-portrait-outline" class="icon-s"></ion-icon>
                      </span> Teléfono: {{atencion.interprete.telefono}}</li>
                  </ul>
                </div>
                <div class="col-lg-5 col-sm-3 align-content-sm-start pt-sm-2 align-self-lg-center">
                  <img src="{{atencion.interprete.avatar.url}}" alt="" class="img-circle img-fluid">
                </div>
              </div>
            </div>
            <div class="card-footer">
              <div class="text-right">
                <a href="#" class="btn btn-sm btn-primary d-flex col-lg-4 col-sm-3 ">
                  <ion-icon name="eye-outline" class="icon-s mr-3 "></ion-icon><span>Ver Perfil</span>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

atencion/templates/atencion/modificarAtencion.html
{% extends 'usuario/solicitante/solicitanteNav.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %}Modificar Atención{% endblock title %}

{% block content_title %}Modificar Atención{% endblock %}

{% block content_breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'dash' %}">Inicio</a></li>
<li class="breadcrumb-item"><a href="{% url 'listado_atenciones' %}">Listado Atenciones</a></li>
<li class="breadcrumb-item active" aria-current="page">Modificar #{{atencion.id}}</li>
{% endblock %}

{% block content %}
<div class="card card-dark">
    <div class="card-header">
        <h3 class="card-title">Modificar Atención - {{atencion.id}}</h3>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <div id="div_fecha_creacion" class="form-group"> 
                <label for="id_fecha_creacion" class=" requiredField">Fecha Creación<span class="asteriskField">*</span></label>
                <div class=""> 
                    <input type="text" name="fecha_creacion" value="{{atencion.fecha_creacion | naturalday}}" disabled="true" class="textinput textInput form-control" required="" id="id_fecha_creacion"> 
                </div>
            </div>
            <div id="div_id_estado" class="form-group"> 
                <label for="id_estado" class=" requiredField">Estado<span class="asteriskField">*</span></label>
                <div class=""> 
                    <input type="text" name="estado" value="{{atencion.get_estado_display | title}}" disabled="true" class="textinput textInput form-control" required="" id="id_estado"> 
                </div>
            </div>
            <button type="submit" class="btn btn-danger" value="Update">Modificar</button>
        </form>
    </div>
</div>
{% endblock %}

atencion/templates/atencion/solicitar.html
{% extends 'usuario/solicitante/solicitarInterprete.html' %}
{% load crispy_forms_tags %}

{% block atencion %}
    <div class="card card-dark">
        <div class="card-header">
            <h3 class="card-title">Solicitud - {{interprete}}</h3>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-danger" value="Save">Solicitar</button>
            </form>
        </div>
    </div>
{% endblock %}